name: run
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: "1.22"
      - name: Tidy
        run: go mod tidy
      - name: Build
        run: go build -v -o build_test .

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: "1.22"
      - name: Lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          config: golangci.yml

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: "1.22"
      - name: Test
        run: go test -race -coverprofile=coverage.out -covermode=atomic -v ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
